@20201008 join responsive
hippo-team/star-front pull request #51
Opened 2020-10-09 13:12 UTC by H0young

basicJoinSelectCard, basicJoinUserCard, basicJoinTitle, JoinSelect, joinUser, 해당 index pages
미디어 쿼리 반응형 style 추가
이후
mq library 사용하여 반응형 구현하여 resolve

2020-10-25 10:04 UTC, Honeyb777 requested changes
수정사항만 수정하지 말고 다른 소스 코드도 보면서 수정해서 올려주세요.
그리고 시간내서 html 구조랑 css 공부좀 했으면 합니다.

2020-10-27 08:08 UTC, H0young commented on components/common/join/basicJoinSelectCard.vue
> +    :class="$mq"
basicButton 컴포넌트 수정, merge 후 일괄 변경 예정
현재는 해당 코드 삭제

2020-10-27 08:09 UTC, H0young commented on components/common/join/basicJoinSelectCard.vue
>    >
image로 변경 완료

2020-10-27 08:09 UTC, H0young commented on components/common/join/basicJoinTitle.vue
> +  /* 반응형 구현 */
삭제 완료

2020-10-27 08:09 UTC, H0young commented on components/common/join/basicJoinUserCard.vue
> +        class="chevron-icon"
수정 완료

2020-10-27 08:10 UTC, H0young commented on components/common/join/basicJoinUserCard.vue
> +          <img
image로 변경 완료

2020-10-27 08:12 UTC, H0young commented on components/common/join/basicJoinUserCard.vue
>          width: width
수정 완료

2020-10-27 08:13 UTC, H0young commented on components/join/joinUser.vue
>    .join-user-cards .join-user-card {
user card 사이 24px 간격이 있음.
:not(:last-child) 적용하여 수정 완료

2020-10-27 08:13 UTC, H0young commented on components/common/join/basicJoinSelectCard.vue
> +  .select-card:hover {
수정 완료!

2020-10-27 08:14 UTC, H0young commented on components/common/join/basicJoinSelectCard.vue
> +  .select-card.mobile .chevron-icon {
자식 요소 스타일에 대한 모든 부모 class 추가 완료

2020-10-27 08:14 UTC, H0young commented on components/common/join/basicJoinSelectCard.vue
> +  .select-card.mobile:hover {
수정 완료!

2020-10-27 08:14 UTC, H0young commented on components/common/join/basicJoinUserCard.vue
> +  .user-card.mobile:hover {
수정 완료!

2020-10-27 08:14 UTC, H0young commented on components/common/join/basicJoinUserCard.vue
>    .user-card:hover {
수정 완료

2020-10-27 08:20 UTC, H0young commented on pages/join/select/index.vue
> +  .join-select-page.mobile {
1. 중복되는 부분은 하나의 스타일로 적용
2. 스타일을 각각 줘야하는 경우 .desktop / .mobile style 로 명시

2020-10-27 08:24 UTC, H0young reviewed
basicButton.vue 컴포넌트 수정 후 일괄 수정할 mousehover 제외 코드 리뷰 받은 부분 및 전체 코드 수정 완료했습니다.

2020-10-27 09:44 UTC, Honeyb777 commented on components/common/join/basicJoinSelectCard.vue
>    >
image 도 문제가됨.

2020-10-27 09:45 UTC, Honeyb777 commented on components/common/join/basicJoinUserCard.vue
> +          <img
image 도 문제가 됨.

2020-10-27 09:47 UTC, Honeyb777 commented on components/common/join/basicJoinSelectCard.vue
> +  .select-card.mobile .chevron-icon {
모든 부모의 class 를 추가 하라는것이 아니라,
구성하는 내용이 달라져서 구분해야 하는 부분에서는 해당 하는 class 를 추가로 작성하여 구분 하도록 요청.

2020-10-27 09:57 UTC, Honeyb777 requested changes
추가 리뷰는 수정사항이 많아서 페이지 켜고 다시 작성하겠습니다.

2020-10-27 09:57 UTC, Honeyb777 commented on components/join/basicJoinUserCard.vue
> +          <img
type-wrap > type-box > type-img 를 타고 내려 왔는데 image 라고 작성하는게 맞는것인지?
component 자체가 join-user 에 대한 component 인데 type 이 붙이는 이유는...?
basic 이라는 단어가 들어가는데 basic 이외에도 다른 형태가 존재 하는지..?

2020-10-28 04:56 UTC, H0young commented on components/join/basicJoinUserCard.vue
> +          <img
1. 해당 데이터가 이미지에 관한 데이터이기 때문에
2. 학생, 부모, 기관, 교수 / 이메일, 네이버, 카카오톡, 페이스북 타입으로 나뉘어서
3. join select의 자식: basic join select, join user의 자식: basic join user

2020-10-28 05:05 UTC, H0young commented on components/join/basicJoinUserCard.vue
> +          <img
부모 클래스 관련: 컴포넌트에서 사용된 관련 없는 '모든' 부모 클래스를 붙였다는 뜻이 아니라 자식 클래스까지 내려오는 데 거쳐온 모든 부모 클래스를 붙였다는 것이었습니다.

2020-11-07 06:15 UTC, Honeyb777 approved these changes
고생하였습니다

2020-11-07 06:15 UTC, merged