[API] jwt 토큰 발급
hippo-team/star-front pull request #53
Opened 2020-10-15 10:25 UTC by ehdals0227

1. @nuxt/axios 설치 후, nuxt.config.js에서 설정.
2. tokenStore.js 라는 store 모듈 추가 후 state, getter, mutations, action 추가 => default.vue에서 mounted 될때마다 호출

2020-10-25 08:18 UTC, Honeyb777 requested changes
추가 수정분을 전달해 merge 처리 하지 않을것으로 생각되기에 request changes 상태로 review

2020-10-25 08:18 UTC, Honeyb777 commented on plugins/axios.js
> +    console.log("Making request to " + config.url)
해당 부분 process.env.NODE_ENV ==="development" 일떄만 보이도록 수정 요청

2020-10-25 08:18 UTC, Honeyb777 commented on plugins/persistedState.js
> +          expires: new Date(Date.now() + minutes * 60 * 1000),
expires 없이 쿠키는 계속 남는건 어떤지..?
계속 남으면 uuid 가 존재하기 때문에 사용자 구분 가능
다만 공용 pc 의 경우 해당 uuid 정보가 다른 사용자 구분을 방해 할 수도 있기 때문에 30분으로 잡는것도 나쁘지는 않은 방법

2020-11-05 10:14 UTC, ehdals0227 commented on plugins/axios.js
> +    console.log("Making request to " + config.url)
완료

2020-11-05 10:14 UTC, ehdals0227 commented on plugins/persistedState.js
> +          expires: new Date(Date.now() + minutes * 60 * 1000),
expires 제거하였음

2020-11-07 04:09 UTC, merged