@20201009 teacher
hippo-team/star-front pull request #55
Opened 2020-10-24 10:07 UTC by seungha-0709

강사 페이지 레이아웃 완성
- hover 등 제플린에 나와 있는 이벤트는 구현했으나, 그 이외의 이벤트는 아직 전혀 삽입 X, 화면 레이아웃 구성만 해 놓은 상태
- 추후 데이터를 받게 되면 동적으로 움직일 수 있도록 수정 예정

2020-10-25 09:22 UTC, Honeyb777 requested changes
수정사항 있습니다.

2020-10-25 09:22 UTC, Honeyb777 commented on components/teacher/radarGraph.vue
> +            },
주석 지워주세요

2020-10-25 09:22 UTC, Honeyb777 commented on components/teacher/radarGraph.vue
> +    <header><h1>세부 항목</h1></header>
header 값도 props 로 받을 수 있으면 좋을것 같은데

2020-10-25 09:22 UTC, Honeyb777 commented on components/teacher/radarGraph.vue
> +          }
주석 지워주세요

2020-10-25 09:22 UTC, Honeyb777 commented on components/teacher/radarGraphChart.vue
> +    mounted() {
주석 지워주세요

2020-10-25 09:22 UTC, Honeyb777 commented on components/teacher/reviewAmount.vue
> +      <div v-if="activeTab === 'review'">
div v-if="activeTab === 'review'">
를
div v-if="activeTab === 'review' || activeTab === 'score' || activeTab === 'passReview'">
형태로 표기 하면 늘어트려서 표기 하는게 아니라 한번에 돌릴 수 있을것 같은데
이렇게 바꾸는거 생각해봐주시고
passreview 는 convention 보고 수정해주세요

2020-10-25 09:22 UTC, Honeyb777 commented on components/teacher/reviewContent.vue
> +            <div class="star-score">
아이콘으로 바꿔주세요

2020-10-25 09:22 UTC, Honeyb777 commented on components/teacher/reviewContent.vue
> +        <article v-for="(review, index) in reviews" :key="index">
해당 부분은 v-if 에서 양쪽을 다 받아서 구분해도 될것 같은 부분인데 확인하고 수정 부탁드립니다.

2020-10-25 09:22 UTC, Honeyb777 commented on components/teacher/teacherTop.vue
> +        </div>
아래 버튼 무한하게 나올 수 있는 버튼이라 반복의 형태로 작성

2020-10-25 09:22 UTC, Honeyb777 commented on components/teacher/teacherTop.vue
> +        </div>
right-button-button-position class 미사용.

2020-10-25 09:22 UTC, Honeyb777 commented on components/teacher/topBanner.vue
> +    background-size: cover;
이미지가 가운데 있어야 합니다.

2020-10-25 09:22 UTC, Honeyb777 commented on package.json
>      "babel-preset-vue": "^2.0.2",
chart.js 지워주세요

CLI 명령어
npm uninstall chart.js

2020-10-25 09:22 UTC, Honeyb777 commented on pages/teacher/index.vue
> +<template>
고생했습니다.
이 페이지는 포트폴리오로 쓰시면 되겠네요.

2020-10-27 02:17 UTC, seungha-0709 commented on assets/data/teacher/teacherSideMenu.js
> +export const menuData = [
수정 완료

2020-10-27 02:38 UTC, seungha-0709 commented on assets/data/teacher/temporaryTeacher.js
> +export const reviewLiveData = [
수정 완료

2020-10-27 02:41 UTC, seungha-0709 commented on assets/data/teacher/temporaryTeacher.js
> +    tag: "#best환승리뷰",
tag항목을 없애고 tagId에 따라 화면에 "#best리뷰" 혹은 "#일반리뷰"로 표기되도록 조건문을 사용하여 수정

2020-10-27 02:46 UTC, seungha-0709 commented on components/teacher/doughnutGraph.vue
> +    <header><h1>수강 유형별 분포</h1></header>
차트 컴포넌트랑 차트를 감싸는 배경 컴포넌트는 제목과 컨텐츠의 개념이라 항상 둘이 붙어다닐 수밖에 없는데 굳이 헤더를 prop으로 넘겨야 하는 이유가 이해가 잘 되지 않습니당....

2020-10-27 03:02 UTC, seungha-0709 commented on components/teacher/doughnutGraph.vue
> +          }
수정 완료

2020-10-27 03:05 UTC, seungha-0709 commented on components/teacher/doughnutGraphChart.vue
> +    mounted() {
수정 완료

2020-10-27 03:10 UTC, seungha-0709 commented on components/teacher/barGraphChart.vue
> +    mounted() {
수정 완료

2020-10-27 03:10 UTC, seungha-0709 commented on components/teacher/radarGraph.vue
> +            },
수정 완료

2020-10-27 03:14 UTC, seungha-0709 commented on components/teacher/doughnutGraph.vue
> +            {
데이터를 상단에서 내려줘야 하는 건 아는데...... 내려줘야 하는 데이터의 형태가 어떤 모양인지를 몰라서.... 어떻게 짜야 할지 몰라 임시로 화면만 우선 그려놓았습니당....

2020-10-27 03:27 UTC, Honeyb777 commented on components/teacher/doughnutGraph.vue
> +    <header><h1>수강 유형별 분포</h1></header>
도넛 차트를 여러개 쓰는 경우 제목을 내려서 사용해야함.
굳이 지금 하나만 쓰고 있고 앞으로도 하나만 쓸 예정이라 그냥 쓸것이다 라고 한다면 강요할 생각은 없음.
추후 수정 할 사람이 다 찾아야 할뿐.

2020-10-27 05:01 UTC, seungha-0709 commented on components/teacher/doughnutGraph.vue
> +          }
수정 완료

2020-10-27 06:47 UTC, seungha-0709 commented on components/teacher/profileMain.vue
> +            <div class="star-score">
일단 v-for랑 v-if는 같이 쓸 수가 없고(빨간줄 뜸)... v-for를 쓰려면 배열이 있어야 하는데... 별 아이콘이 각각 1개당 조건식이 쓰여서 얘네들을 어떻게 배열로 만들어야 할지 잘 모르겠고...ㅠㅠ 어떻게 코드를 줄여야 할지 잘 모르겠어요......ㅠㅠ

2020-10-27 07:27 UTC, seungha-0709 commented on components/teacher/profileSide.vue
> +      <h2>
수정 완료

2020-10-27 07:28 UTC, seungha-0709 commented on components/teacher/profileMain.vue
> +              ><span class="total-score">{{ `/${score.total}` }}</span>
수정 완료

2020-10-27 07:28 UTC, seungha-0709 commented on components/teacher/radarGraph.vue
> +          }
수정 완료

2020-10-27 07:28 UTC, seungha-0709 commented on components/teacher/radarGraphChart.vue
> +    mounted() {
수정 완료

2020-10-27 07:50 UTC, seungha-0709 commented on components/teacher/barGraph.vue
> +    <header><h1>리뷰 분포</h1></header>
수정 완료

2020-10-27 07:50 UTC, seungha-0709 commented on components/teacher/doughnutGraph.vue
> +    <header><h1>수강 유형별 분포</h1></header>
네 수정했습니당

2020-10-27 07:51 UTC, seungha-0709 commented on components/teacher/radarGraph.vue
> +    <header><h1>세부 항목</h1></header>
수정 완료

2020-10-30 02:15 UTC, seungha-0709 commented on components/teacher/teacherTop.vue
> +        </div>
수정 완료

2020-10-30 02:15 UTC, seungha-0709 commented on components/teacher/teacherTop.vue
> +        </div>
삭제 완료

2020-10-30 02:18 UTC, seungha-0709 commented on components/teacher/topBanner.vue
> +    background-size: cover;
수정 완료

2020-10-30 02:23 UTC, seungha-0709 commented on package.json
>      "babel-preset-vue": "^2.0.2",
삭제 완료

2020-10-30 02:25 UTC, seungha-0709 commented on package.json
>      "babel-preset-vue": "^2.0.2",
삭제했더니 vue-chart.js에는 chart.js가 필요하다는 에러가 떠서 다시 설치.....

2020-10-30 03:08 UTC, seungha-0709 commented on components/teacher/teacherTop.vue
> +        </div>
제플린 확인해보니 창문처럼 생긴 아이콘을 클릭하면 모달처럼 아래에 박스가 하나 뜨면서 거기에 다른 강의 과목이 나열되어 있길래 그렇게 구현해 놓았습니다

2020-10-30 03:08 UTC, seungha-0709 commented on components/teacher/teacherTop.vue
> +        </div>
![image](https://user-images.githubusercontent.com/68048716/97655539-a5989400-1aa8-11eb-9a6b-9d6fa6f911ce.png)

2020-10-30 03:10 UTC, seungha-0709 commented on components/teacher/reviewContent.vue
> +            <div class="star-score">
수정 완료

2020-10-30 03:24 UTC, seungha-0709 commented on components/teacher/reviewContent.vue
> +        <article v-for="(review, index) in reviews" :key="index">
무슨 말인지 이해를 못하였음...... 어떻게 무엇을 양쪽을 다 받아서 구분하라는 말인지....? ㅠㅠ

2020-10-30 03:36 UTC, seungha-0709 commented on components/teacher/reviewAmount.vue
> +      <div v-if="activeTab === 'review'">
이게 지금은 데이터가 안 들어가서 똑같은 형태가 반복되는 것처럼 보이는데 각각의 탭마다 들어가는 데이터가 달라서 한번에 돌리는 건 부적절하다고 생각합니다..... 데이터가 어떤 모양으로 내려올지를 몰라서 수정하기가 어려운 부분....

2020-11-01 20:24 UTC, seungha-0709 commented on components/teacher/profileMain.vue
> +            <div class="star-score">
수정 완료

2020-11-01 20:28 UTC, seungha-0709 commented on components/teacher/reviewContent.vue
> +        <article v-for="(review, index) in reviews" :key="index">
v-if에서 양쪽을 다 받게끔 해줬더니 화면이 깨집니다..

2020-11-02 02:04 UTC, seungha-0709 commented on components/teacher/doughnutGraph.vue
> +            {
수정 완료 (데이터는 임시이기 때문에 따로 빼지 않고 그냥 index.vue에서 정의했습니다 왜 데이터를 따로 빼지 않았냐고 하지 마세영 어차피 나중에 삭제할 것임)

2020-11-02 02:04 UTC, seungha-0709 commented on components/teacher/barGraph.vue
> +        this.dataCollection = {
위와 동일. 수정 완료

2020-11-07 04:50 UTC, Honeyb777 requested changes

2020-11-07 04:50 UTC, Honeyb777 commented on components/teacher/profileMain.vue
> +            <div class="star-score">
재수정 요청

2020-11-07 04:50 UTC, Honeyb777 commented on components/teacher/reviewContent.vue
> +        <article v-for="(review, index) in reviews" :key="index">
재수정 요청

2020-11-07 04:50 UTC, Honeyb777 commented on components/teacher/reviewLive.vue
> +      >
합쳐주세요

2020-11-07 06:03 UTC, seungha-0709 commented on components/teacher/reviewLive.vue
> +      >
안 하기로 한 두 번째 수정요청사항 빼고 나머지 모두 수정 완료

2020-11-07 06:08 UTC, Honeyb777 approved these changes
고생하였습니다

2020-11-07 06:08 UTC, merged